### PR TITLE
Adding files needed for swagger-ui hosted on Github Pages

### PR DESCRIPTION
**Pull request by ajitdsa**
Types of changes
----------------
- New feature (non-breaking change which adds functionality)
- Documentation

Description
-----------
Adding files needed for swagger-ui hosted on Github Pages.
Also moved openapi.yml file to the docs directory and changed references to it in code.

The code in this branch has not explicitly been tested, as it needs to be uploaded first, but I did follow the instructions here https://github.com/peter-evans/swagger-github-pages in order to create a test version of this in my personal github account: https://ajitdsa.github.io/swagger-ui-test/ (repo: https://github.com/ajitdsa/swagger-ui-test) and that works.

I also added a script to add symlinks locally and instructions in the README for this so that you can view the docs in Swagger UI easily on your local machine.

Note:
----------
After this branch has been merged, in the settings for this repository there will be an option under the GitHub Pages section for the Source to be `master branch /docs folder`, which will need to be selected in order to make this work. And anecdotally, it seems to take about a minute for the Github Page to work.

Checklist:
----------
- [X] I have updated the documentation accordingly
- [] I have updated the Changelog (if applicable)

There was no issue for this fix.

### CODE REVIEW

**Comment by ajitdsa** [comment]
@rgreinho For some reason I couldn't get it to work on my local either. That's why I created the test repo. 🤷‍♂

**Comment by rgreinho** [comment]
The paths for the scripts are incorrect. They should be:

```js
  <link rel="stylesheet" type="text/css" href="swagger-ui-3.25.0/dist/swagger-ui.css">
  <link rel="icon" type="image/png" href="swagger-ui-3.25.0/dist/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="swagger-ui-3.25.0/dist/favicon-16x16.png" sizes="16x16" />
  <script src="swagger-ui-3.25.0/dist/swagger-ui-bundle.js"> </script>
  <script src="swagger-ui-3.25.0/dist/swagger-ui-standalone-preset.js"> </script>
```

Then it sill complains about not being able to read the local openapi file though:

image

**Comment by rgreinho** [comment]
This issue may help you @ajitdsa: https://github.com/swagger-api/swagger-ui/issues/1110.

**Comment by rgreinho** [comment]
Also, JavaScript cannot read the YAML directly, you will either have to parse it or convert it to json.

**Comment by ajitdsa** [comment]
Yes, you're right about the paths! I forgot that I included the entire swagger directory to make it easier for us to change versions later and such. Okay, I added that.

Screen Shot 2020-03-05 at 9 22 08 AM

Regarding the local issue, it appears to be a CORS thing (see the highlighted section of the screenshot above) which wouldn't happen if you set up a web server and ran it locally on the web server. For instance, I did that locally and it worked fine:

Screen Shot 2020-03-05 at 10 40 25 AM

Finally, I don't think your last statement about Javascript not being able to read YAML is correct. First of all, it doesn't make sense. It's just a file. Second, if you looks at my test site https://ajitdsa.github.io/swagger-ui-test/ it is totally reading the YAML file just fine.

**Comment by ajitdsa** [comment]
Note:
To get the local thing working, I had to set up some local symbolic links:

```
➜  commerce-api git:(adding-swagger-ui) ✗ ls -la public 
total 8
drwxr-xr-x   6 ajitdsa  staff  192 Mar  5 09:43 .
drwxr-xr-x  26 ajitdsa  staff  832 Mar  5 07:38 ..
lrwxr-xr-x   1 ajitdsa  staff   18 Mar  5 09:42 index.html -> ../docs/index.html
lrwxr-xr-x   1 ajitdsa  staff   19 Mar  5 09:42 openapi.yml -> ../docs/openapi.yml
-rw-r--r--   1 ajitdsa  staff   99 Mar  3 06:53 robots.txt
lrwxr-xr-x   1 ajitdsa  staff   25 Mar  5 09:43 swagger-ui-3.25.0 -> ../docs/swagger-ui-3.25.0
```

I think maybe we should set up a bash script to create (and remove if we'd like) these symbolic links to make it easy to run locally. What do you think?

**Comment by rgreinho** [comment]
Hmmm, I still have the same error message, even with the latest changes and the symlinks :cry:

image

I was not saying that JS cannot read a file, just that by default, it cannot parse YAML. In JS you can do `JSON.parse()`, but not `YAML.parse()`. But swagger-ui has a YAML parser, so it's no big deal and that's why it works.

**Comment by ajitdsa** [comment]
@rgreinho I don't get it. Why is the browser URL `File /Users/remygreinhofer/.../index.html`? That implies you aren't accessing the webserver. You should be starting the Rails server and then accessing http://localhost:3000, otherwise you'll get the CORS issue. I put instructions for this in the README. Are they not clear?

**Comment by rgreinho** [comment]
Oh that makes sense! The file has to be served by a webserver! Now it works 😅

**Pull request merged**
