### PR TITLE
BluePrince Configuration

### LINKED ISSUE #18: Blue Prince Configuration values
BluePrince config values should be available. 

Current Behavior
----------------
There is currently no quick way to customize important things in BluePrince, beyond changing the actual code. 

Expected Behavior
-----------------
Implementers should be able to change configuration values in `initializers/blue_prince_config.rb` which are then subsequently reflected in the BluePrince generator.

Possible Solution
-----------------
Make the values in `initializers/blue_prince_config.rb` available to and used in BluePrince.

### PR DESCRIPTION
**Pull request by eheiberg**
In order to aid in configuration, we have added controller methods to the security controller that help with deriving the page and limit variables that we would normally pull from the params directly.

Types of changes
----------------
- New feature (non-breaking change which adds functionality)

Description
-----------
Adds configuration options to BluePrince that can be set from an initializer. 

Checklist:
----------
- [x] I have updated the documentation accordingly
- [] I have updated the Changelog (if applicable)

close #18 for now at least.

### CODE REVIEW

**Comment by ajitdsa** [comment]
Is the feeling that these don’t really belong in strong params?

**Comment by ajitdsa** [comment]
Oh wait... the strong params are still there. Based on the code I’m not 100% sure I get this. It looks like `params[:page]` is still used in places to where if you renamed it in the config file that it would break.

Also I would be fine just reserving those param names and not letting you change them.

**Comment by eheiberg** [comment]
@ajitdsa Hmmm.. I will check. There shouldn't be any references to `page[:param]`.

**Comment by eheiberg** [comment]
HAHA. I'm an idiot. Fixing now

**Comment by eheiberg** [comment]
OK! Let's use `params[:page]` as an example

- If you search through the project and you see this in any generated controller, then it's fine. 
- If you search through the project and you see this in anything that is helping to generate the controller, then it is NOT fine. 

So, if your config is set to make `page` the paging param (i.e. the default), then your `SecurityController` will make a direct reference to `params[:page]` like it's supposed to. 

NOTE: `SecurityController` is generated!

In the generator, `lib/generators/blue_prince/templates/generated_security_controller.erb` you'll see that the paging variable is being pulled from the `BluePrince.configuration` like it's supposed to.

Do you see any other places where I might have messed this up? Does what I said address what you're talking about?

**Pull request merged**
